In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("student_performance.csv")

### How many rows and columns are there in the dataset?

In [ ]:
df.shape

(1000000, 6)

### Show the first 10 rows of the dataset.

In [ ]:
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [ ]:
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999990,999991,15.4,82.8,4.0,86.9,A
999991,999992,30.0,87.4,6.7,100.0,A
999992,999993,26.3,84.6,4.5,100.0,A
999993,999994,20.7,82.4,5.5,99.1,A
999994,999995,15.1,77.0,9.2,80.5,B
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### What are the column names in the dataset?

In [ ]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

### What is the maximum value of weekly_self_study_hours?

In [ ]:
df['weekly_self_study_hours'].max()

40.0

### Which student studied the most hours in a week?

In [ ]:
df[df['weekly_self_study_hours'] == df['weekly_self_study_hours'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
209,210,40.0,68.1,6.7,100.0,A
2895,2896,40.0,75.7,4.2,100.0,A
15843,15844,40.0,99.5,8.0,100.0,A
18851,18852,40.0,91.7,7.0,100.0,A
20126,20127,40.0,94.1,3.0,100.0,A
...,...,...,...,...,...,...
971477,971478,40.0,74.2,7.7,100.0,A
973306,973307,40.0,90.0,6.2,100.0,A
974300,974301,40.0,78.8,2.5,100.0,A
976629,976630,40.0,93.9,7.0,100.0,A
980167,980168,40.0,82.6,7.2,100.0,A

### Show the top 5 students by weekly_self_study_hours.

In [ ]:
df.sort_values('weekly_self_study_hours', ascending=False).head(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
779223,779224,40.0,76.1,6.4,100.0,A
891941,891942,40.0,72.6,8.8,100.0,A
334965,334966,40.0,92.3,5.4,100.0,A
912897,912898,40.0,100.0,9.1,100.0,A
628230,628231,40.0,93.4,5.2,100.0,A

### Which student has the highest attendance percentage?

In [ ]:
std = df[df['attendance_percentage'] == df['attendance_percentage'].max()].count()['student_id']
total = df.shape[0]
per = (std * 100) / total
print(per)

6.7378

### Which student has the highest class participation?

In [ ]:
df['attendance_percentage'].max()

100.0

### Create a new column score_level
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

### Which student has the highest total_score?

### How many students scored exactly 100 in total_score?

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

### Create a new column study_category
"Light" if weekly_self_study_hours < 10,
"Moderate" if 10 ≤ hours ≤ 20,
"Heavy" if hours > 20